### ISSUE TITLE
plugin is not playing well with setters

### ISSUE THREAD

**Issue by TrejGun** [getlackey/mongoose-version#3]
``` js
"use strict";

process.env.NODE_ENV = "development";

import mongoose, {Schema} from "mongoose";
import mongooseVersion from "lackey-mongoose-version";


let Test = new Schema({
    first: {
        type: Boolean
    },
    second: {
        type: Boolean
    }
}, {versionKey: false});

Test.path("first", {
    set: function (first) {
        this.first = this.second;
        return first;
    }
});

Test.plugin(mongooseVersion, {
    collection: "TestVersions",
    mongoose: mongoose
});

export default Event;
```

throws error

```
➜  test git:(master) ✗ ./node_modules/.bin/babel-node --stage=0 test.js
.../node_modules/mongoose/lib/schema.js:530
    throw new TypeError('Undefined type `' + name + '` at `' + path +
          ^
TypeError: Undefined type `Set` at `first.set`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (.../node_modules/mongoose/lib/schema.js:530:11)
    at Schema.path (.../node_modules/mongoose/lib/schema.js:461:29)
    at Schema.add (.../node_modules/mongoose/lib/schema.js:356:12)
    at Schema.add (.../node_modules/mongoose/lib/schema.js:351:14)
    at .../node_modules/lackey-mongoose-version/lib/clone-schema.js:15:22
    at Schema.eachPath (.../node_modules/mongoose/lib/schema.js:553:5)
    at module.exports (.../node_modules/lackey-mongoose-version/lib/clone-schema.js:9:12)
    at module.exports (.../node_modules/lackey-mongoose-version/lib/save-collection.js:10:27)
    at module.exports (.../node_modules/lackey-mongoose-version/lib/version.js:23:5)
    at Schema.plugin (.../node_modules/mongoose/lib/schema.js:806:3)
    at Object.<anonymous> (.../test.js:25:7)
    at Module._compile (module.js:460:26)
    at normalLoader (.../node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (.../node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

but this code works just fine

``` js
let Test = new Schema({
    first: {
        type: Boolean,
        set: function (first) {
            this.second = this.first;
            return first;
        }
    },
    second: {
        type: Boolean
    }
});
```

**Comment by robmccardle** [comment]
Thanks for getting in touch; we're a bit short handed at the moment so can't resource anyone to look at this right now I'm afraid. I know @melono6 would welcome a pull request if you get setters working, I'll mark and leave this open

**Comment by TrejGun** [comment]
fix is published as 
https://www.npmjs.com/package/@trejgun/mongoose-versions
